[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[git]
deploymentEnabled.backend = true
deploymentEnabled.main = false
deploymentEnabled.frontend = false
