name: Railway Backend Deploy

on:
  push:
    branches: [ backend ]
  workflow_dispatch:  # 수동 트리거 가능

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
    
    - name: Login to Railway
      run: railway login --token ${{ secrets.RAILWAY_TOKEN }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Deploy to Railway
      run: railway up --service backend
      working-directory: ./backend
