name: Railway Backend Deploy

on:
  push:
    branches: [ backend ]
  workflow_dispatch:  # 수동 트리거 가능

jobs:
  notify-railway:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Notify Railway Deployment
      run: |
        echo "Backend branch updated. Railway should auto-deploy via webhook."
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Repository: ${{ github.repository }}"
        
        # Railway 웹훅 트리거 (Railway 대시보드에서 설정된 경우)
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "ref": "${{ github.ref }}",
            "repository": {
              "full_name": "${{ github.repository }}",
              "clone_url": "${{ github.server_url }}/${{ github.repository }}.git"
            },
            "head_commit": {
              "id": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}"
            }
          }' \
          "${{ secrets.RAILWAY_WEBHOOK_URL }}" || echo "Webhook not configured, Railway auto-deploy should handle this"
